apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 2
  selector:
    matchLabels: { app: demo }
  template:
    metadata: { labels: { app: demo } }
    spec:
      containers:
        - name: web
          image: ghcr.io/luneski/kubernetes-learning-demo:dev
          ports: [{ containerPort: 8080 }]
          env:
            - name: PORT
              value: "8080"
